services:
    Fourxxi\ApiUserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

    api_user.provider.credentials_plain: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\PlainCredentialsProvider'
    api_user.provider.credentials_bearer: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\BearerCredentialsProvider'
    api_user.provider.credentials:
        alias: 'api_user.provider.credentials_plain'

    api_user.base_token_credentials_generator: '@Fourxxi\ApiUserBundle\Service\TokenGenerator'
    api_user.token_credentials_generator:
        alias: 'api_user.base_token_credentials_generator'
    api_user.confirmation_token_credentials_generator:
        alias: 'api_user.base_token_credentials_generator'

    api_user.provider.token_repository:
        class: Fourxxi\ApiUserBundle\Repository\TokenRepository
        arguments:
            $registry: '@doctrine'
            $tokenLifetime: '%api_user.token_lifetime%'
            $credentialsGenerator: '@api_user.token_credentials_generator'

    api_user.provider.confirmation_token_repository:
        class: Fourxxi\ApiUserBundle\Repository\ConfirmationTokenRepository
        arguments:
            $registry: '@doctrine'
            $credentialsGenerator: '@api_user.confirmation_token_credentials_generator'

    api_user.provider.token:
        alias: 'api_user.provider.token_repository'

    api_user.provider.confirmation_token:
        alias: 'api_user.provider.confirmation_token_repository'

    api_user.token_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\TokenAuthenticator
        arguments:
            $credentialsProvider: '@api_user.provider.credentials'
            $tokenProvider: '@api_user.provider.token'
            $eventDispatcher: '@event_dispatcher'

    api_user.json_login_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\JsonLoginAuthenticator
        arguments:
            $tokenProvider: '@api_user.provider.token'
            $passwordEncoder: '@security.password_encoder'
            $eventDispatcher: '@event_dispatcher'

    api_user.router:
        class: Fourxxi\ApiUserBundle\Routing\ApiUserLoader
        tags:
            - 'routing.loader'

    api_user.registration.form_type:
        alias: 'Fourxxi\ApiUserBundle\Form\Type\UserRegistrationType'

    Fourxxi\ApiUserBundle\Controller\RegistrationController:
        arguments:
            $registrationFormType: '@api_user.registration.form_type'
            $userClass: '%api_user.user_class%'
            $eventDispatcher: '@event_dispatcher'
        tags: ['controller.service_arguments']

    Fourxxi\ApiUserBundle\EventSubscriber\EncodeUserPasswordSubscriber:
        arguments:
            $passwordEncoder: '@security.password_encoder'
        tags: ['kernel.event_subscriber']


