services:
    Fourxxi\ApiUserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

    api_user.provider.credentials_plain: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\PlainCredentialsProvider'
    api_user.provider.credentials_bearer: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\BearerCredentialsProvider'
    api_user.provider.credentials:
        alias: 'api_user.provider.credentials_plain'

    api_user.base_token_credentials_generator: '@Fourxxi\ApiUserBundle\Service\TokenGenerator'
    api_user.token_credentials_generator:
        alias: 'api_user.base_token_credentials_generator'
    api_user.confirmation_token_credentials_generator:
        alias: 'api_user.base_token_credentials_generator'

    api_user.provider.token_repository:
        class: Fourxxi\ApiUserBundle\Repository\TokenRepository
        arguments:
            $registry: '@doctrine'
            $tokenLifetime: '%api_user.token_lifetime%'
            $credentialsGenerator: '@api_user.token_credentials_generator'

    api_user.provider.token:
        alias: 'api_user.provider.token_repository'

    api_user.token_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\TokenAuthenticator
        arguments:
            $credentialsProvider: '@api_user.provider.credentials'
            $tokenProvider: '@api_user.provider.token'
            $eventDispatcher: '@event_dispatcher'

    api_user.json_login_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\JsonLoginAuthenticator
        arguments:
            $tokenProvider: '@api_user.provider.token'
            $passwordEncoder: '@security.password_encoder'
            $eventDispatcher: '@event_dispatcher'

    api_user.router:
        class: Fourxxi\ApiUserBundle\Routing\ApiUserLoader
        tags:
            - 'routing.loader'

    api_user.registration.form_type:
        alias: 'Fourxxi\ApiUserBundle\Form\Type\UserRegistrationType'

    Fourxxi\ApiUserBundle\Controller\RegistrationController:
        arguments:
            $registrationFormType: '@api_user.registration.form_type'
            $userClass: '%api_user.user_class%'
            $formFactory: '@form.factory'
            $entityManager: '@doctrine.orm.entity_manager.abstract'
            $eventDispatcher: '@event_dispatcher'
        tags: ['controller.service_arguments']

    Fourxxi\ApiUserBundle\Controller\ConfirmationController:
        arguments:
            $userClass: '%api_user.user_class%'
        tags: ['controller.service_arguments']

    Fourxxi\ApiUserBundle\EventSubscriber\EncodeUserPasswordSubscriber:
        arguments:
            $passwordEncoder: '@security.password_encoder'
        tags: ['kernel.event_subscriber']

    Fourxxi\ApiUserBundle\Service\FrontendRouter:
        arguments:
            $baseUrl: '%api_user.frontend.base_url%'
            $confirmationRoute: '%api_user.confirmation.frontend_route%'

    Fourxxi\ApiUserBundle\EventSubscriber\UserConfirmationSubscriber:
        arguments:
            $credentialsGenerator: '@api_user.confirmation_token_credentials_generator'
            $messageSender: '@api_user.message_sender'
            $router: '@Fourxxi\ApiUserBundle\Service\FrontendRouter'
        tags: ['kernel.event_subscriber']

    api_user.user_checker:
        public: true
        class: Fourxxi\ApiUserBundle\Security\UserChecker
        arguments:
            $confirmationEnabled: '%api_user.confirmation_enabled%'
            $allowUnconfirmedLogin: '%api_user.allow_unconfirmed_login%'

    api_user.message_sender:
        alias: 'api_user.message_sender.plain_email'

    api_user.message_sender.plain_email:
        class: Fourxxi\ApiUserBundle\Sender\PlainMailerSender
        arguments:
            $from: '%api_user.message_sender.from%'
            $mailer: '@mailer'
            $translator: '@translator'
            $logger: '@logger'

