services:
    Fourxxi\ApiUserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

    api_user.provider.credentials_plain: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\PlainCredentialsProvider'
    api_user.provider.credentials_bearer: '@Fourxxi\ApiUserBundle\Provider\Security\Guard\BearerCredentialsProvider'
    api_user.provider.credentials:
        alias: 'api_user.provider.credentials_plain'

    api_user.provider.token_repository_user:
        class: Fourxxi\ApiUserBundle\Repository\TokenRepository
        arguments:
            $registry: '@doctrine'

    api_user.provider.user:
        alias: 'api_user.provider.token_repository_user'

    api_user.token_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\TokenAuthenticator
        arguments:
            $credentialsProvider: '@api_user.provider.credentials'
            $userProvider: '@api_user.provider.user'
            $eventDispatcher: '@event_dispatcher'

    api_user.json_login_authenticator:
        public: true
        class: Fourxxi\ApiUserBundle\Security\Guard\JsonLoginAuthenticator

    api_user.router:
        class: Fourxxi\ApiUserBundle\Routing\ApiUserLoader
        tags:
            - 'routing.loader'
