Fourxxi\ApiUserBundle\Entity\Token:
  type: entity
  repositoryClass: Fourxxi\ApiUserBundle\Repository\TokenRepository
  table: api_user_token
  indexes:
    credentials_index:
      columns: [ expires_at, credentials ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expiresAt:
      type: datetime_immutable
    credentials:
      type: string
  manyToOne:
    user:
      targetEntity: Symfony\Component\Security\Core\User\UserInterface
      joinColumn:
        onDelete: CASCADE